update manifests script

diff --git a/bin/manifest b/bin/manifest
--- a/bin/manifest
+++ b/bin/manifest
@@ -13,7 +13,7 @@ REPO_PATH=${REPO_PATH:-$DIR/../src}
 ################################################################################
 # source bash libs
 ################################################################################
-# shellcheck source=./../build-harness/lib/bash.sh
+# shellcheck source=../lib/bash.sh
 source "${DIR}/../lib/bash.sh"
 
 ################################################################################
@@ -31,8 +31,8 @@ usage() {
     echo "options:"
     echo "  -h      Print this Help."
     echo
-    echo "This script reads from a local file named repo-manifest which is expected"
-    echo "to include a list of github repos one repo per line as "
+    echo "This script reads from a local file manifests/repos which is expected"
+    echo "to include a list of git repos repos one repo per line as "
     echo "{remote_repo_url} {local_repo}"
     echo 
     echo "a repo may reference a specific branch or tag"
@@ -43,7 +43,7 @@ usage() {
 ################################################################################
 # validate requirements
 ################################################################################
-[ -f "$DIR"/../../repo-manifest ] || ( usage && die "repo-manifest flle not found" )
+[ -f "$DIR"/../../manifests/repos ] || ( usage && die "manifests/repos flle not found" )
 
 ################################################################################
 # Process the input options. Add options as needed.                            #
@@ -95,4 +95,4 @@ do
             ;;
     esac
 
-done < "$DIR"/../../repo-manifest
+done < "$DIR"/../../manifests/repos
